# Generated by Django 4.1.4 on 2022-12-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TankTiviteit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=140)),
                ('aanmaakmoment', models.DateTimeField(auto_now_add=True, verbose_name='Aangemaakt op')),
                ('wanneer', models.DateField(verbose_name='Tanktiviteit moment')),
            ],
        ),
        migrations.CreateModel(
            name='Inschrijvign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opmerkingen', models.CharField(max_length=140)),
                ('tanktiviteit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenementen.tanktiviteit')),
            ],
        ),
    ]
