# Generated by Django 4.1.4 on 2022-12-25 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenementen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inschrijvign',
            new_name='Inschrijving',
        ),
    ]
