# Generated by Django 4.1.4 on 2022-12-25 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evenementen', '0002_rename_inschrijvign_inschrijving'),
    ]

    operations = [
        migrations.AddField(
            model_name='inschrijving',
            name='plaatser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inschrijvingen', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inschrijving',
            name='tanktiviteit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inschrijvingen', to='evenementen.tanktiviteit'),
        ),
    ]
