# Generated by Django 4.1.4 on 2022-12-25 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evenementen', '0003_inschrijving_plaatser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanktiviteit',
            name='beschrijving',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanktiviteit',
            name='gemaakt_door',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tanktiviteit',
            name='prijs',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanktiviteit',
            name='sluiting',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='De inschrijvingen sluiten om'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tanktiviteit',
            name='wanneer',
            field=models.DateTimeField(verbose_name='Tanktiviteit moment'),
        ),
    ]
