# Generated by Django 4.1.4 on 2022-12-27 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evenementen', '0005_remove_inschrijving_plaatser'),
    ]

    operations = [
        migrations.AddField(
            model_name='inschrijving',
            name='plaatser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inschrijvingen', to=settings.AUTH_USER_MODEL),
        ),
    ]
