# Generated by Django 4.1.4 on 2022-12-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenementen', '0006_inschrijving_plaatser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanktiviteit',
            name='prijs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Prijs'),
        ),
    ]
