# Generated by Django 4.1.4 on 2022-12-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenementen', '0008_tanktiviteit_plaatje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanktiviteit',
            name='plaatje',
            field=models.ImageField(default='images/tank.jpg', upload_to='images/'),
        ),
    ]
