# Generated by Django 4.1.4 on 2022-12-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenementen', '0009_alter_tanktiviteit_plaatje'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanktiviteit',
            name='max_inschrijvingen',
            field=models.PositiveSmallIntegerField(default=76),
        ),
    ]
