# Generated by Django 4.1.4 on 2022-12-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenementen', '0011_tanktiviteit_verantwoordelijke_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanktiviteit',
            name='tankrekening',
            field=models.BooleanField(default=True),
        ),
    ]
