# Generated by Django 4.1.4 on 2023-01-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenementen', '0012_tanktiviteit_tankrekening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inschrijving',
            name='opmerkingen',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
